apiVersion: v1
kind: pod
metadata: 
  name: masterpod
spec:
  containers:
   - name: yamimastercontainer
     image: yuvarajnbkr2015/master
     ports:
      - name: web
        containerPort: 8080
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 15
      failureThreshold: 3
